name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    - run: npm publish
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
            - uses: actions/labeler@v4
          with:
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
          with:
            node-version: 16
            registry-url: https://npm.pkg.github.com/
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
